version: '3.8'

services:
  backend:
    build: ./backend
    restart: always
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
      - /app/venv
    environment:
      - FLASK_APP=run.py
      - FLASK_ENV=production
      - FLASK_DEBUG=0
    networks:
      - app-network

  frontend:
    build: ./frontend
    restart: always
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    environment:
      - VITE_API_URL=http://backend:5000
    networks:
      - app-network

networks:
  app-network:
    driver: bridge 